---
language: node_js
node_js:
  - stable
env:
  - EMBER_VERSION=default
  - EMBER_VERSION=release
  - EMBER_VERSION=beta
  - EMBER_VERSION=canary

matrix:
  allow_failures:
    - env: EMBER_VERSION=canary

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - npm test
